import json
import os
import shutil

def load_cmake_presets(presets_path):
    print(f"📄 Loading {presets_path}...")
    with open(presets_path, "r") as f:
        return json.load(f)

def resolve_binary_dirs(presets, source_dir):
    dirs = []
    print("🔍 Resolving binary directories from presets...")
    for preset in presets.get("configurePresets", []):
        name = preset.get("name", "<unnamed>")
        binary_dir = preset.get("binaryDir")
        if binary_dir:
            binary_dir = binary_dir.replace("${sourceDir}", source_dir)
            binary_dir = os.path.normpath(binary_dir)
            print(f"  - Preset '{name}' => {binary_dir}")
            dirs.append((name, binary_dir))
    return dirs

def clean_build_dirs(dirs):
    print("\n🧹 Cleaning build directories...")
    removed = 0
    skipped = 0
    for name, d in dirs:
        if os.path.exists(d):
            print(f"✅ Removing [{name}]: {d}")
            shutil.rmtree(d)
            removed += 1
        else:
            print(f"⏭  Skipping [{name}] (not found): {d}")
            skipped += 1
    return removed, skipped

def main():
    tools_dir = os.path.abspath(os.path.dirname(__file__))
    root_dir = os.path.abspath(os.path.join(tools_dir, ".."))
    presets_path = os.path.join(root_dir, "CMakePresets.json")

    try:
        presets = load_cmake_presets(presets_path)
        binary_dirs = resolve_binary_dirs(presets, root_dir)
        removed, skipped = clean_build_dirs(binary_dirs)
        print(f"\n✅ Done. Removed: {removed}, Skipped: {skipped}")
    except FileNotFoundError:
        print(f"❌ Error: CMakePresets.json not found at {presets_path}")
    except json.JSONDecodeError as e:
        print(f"❌ Error parsing JSON: {e}")
    except Exception as e:
        print(f"❌ Unexpected error: {e}")

if __name__ == "__main__":
    main()


# Generated by ChatGPT.
# This script cleans up build directories defined in CMakePresets.json
# It resolves the binary directories based on the source directory and removes them if they exist.
# Usage: From your project root:
# > python tools/clean.py
# Ensure you have a CMakePresets.json file in the same directory as this script.